### ISSUE TITLE
Look into easier method of data input for variable data

### ISSUE THREAD

**Issue by malberto23** [FlightLabsUNSW/FLU-AUVSI-Interop-System#4]
Maybe have a JSON or TXT file with the username, password, interop IP & port, and mission ID all in one, then have the program open, and prompt user to confirm values are correct?

**Comment by Anthony-1811** [comment]
Agreed. A txt config file is the way to go. Either in CSV or new line separated. Makes the code way simpler since there’s only a few variables.

**Comment by malberto23** [comment]
Completed using JSON - easy implementation with a function and editing is also easy. Done for 2020 system only.
