### ISSUE TITLE
Implement system into full Linux environment

### ISSUE THREAD

**Issue by malberto23** [FlightLabsUNSW/FLU-AUVSI-Interop-System#5]
**** BIG CHANGES REQUIRED ****
Anticipating a potential move away from Windows for the system
- Investigate potential for using a full-Linux system
- Move code from PS to Python (probably easiest)
- Reorganise repo into two folders for Windows/Linux and full Linux solutions

**NOTE:** May require significant time and effort, potential summer project to mess around with this and get it all working as it currently is on the hybrid Windows/Linux VM system

**Comment by Anthony-1811** [comment]
IMO Bash would probably be easier instead of Python.

**Comment by Eddyyy** [comment]
I am wondering tho if you could hook into ros directly and then sending the data to the server without even needing a file server for transmission. You could even query the user directly from python and the you wouldn't even worry about zipping or any sort of file f*ck around except for saving for later and even then.
May even make the interop system much simpler and faster using the python api libraries. 
Subscribe to topic, receive dictionary and image, make json string and pipe to api without leaving ram.

**Comment by Eddyyy** [comment]
http://wiki.ros.org/rospy_message_converter
lol

**Comment by malberto23** [comment]
@Eddyyy if you're happy to lead that integration then I'm all for it - I'll just be a bit lost... :P
For now I've just migrated everything over using Bash and it's already quite less complicated and integrates much easier. Still working on a few other bits and pieces but the main scripts are done.

**Comment by malberto23** [comment]
Going to close this now, as the majority of the code is now complete.
